parameters:
    datatable.class: Ali\DatatableBundle\Util\Datatable

services:
    datatable:
        class: "%datatable.class%"
        arguments: ['@service_container']
        scope: prototype
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            
    datatable.twig.extension:
        class: Ali\DatatableBundle\Twig\Extension\AliDatatableExtension
        arguments: ['@service_container']
        tags:
            -  { name: twig.extension }
            
    datatable.listener:
        class: Ali\DatatableBundle\EventListener\DatatableListener
        arguments: [ '@twig' ]
        tags:
            - { name: kernel.event_listener, event: kernel.response,  method: onKernelResponse, priority: 255 }
