parameters:
    datatable.class: Ali\DatatableBundle\Util\Datatable

services:
    datatable:
        class: "%datatable.class%"
        arguments: [ @service_container ]
        scope: prototype
        
    datatable.twig.extension:
        class: Ali\DatatableBundle\Twig\Extension\AliDatatableExtension
        arguments: [ @service_container ]
        tags:
            -  { name: twig.extension }
    
    datatable.kernel.listener.terminate:
        class: Ali\DatatableBundle\Listener\KernelTerminateListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }