parameters:
    datatable.class: Ali\DatatableBundle\Util\Datatable

services:
    datatable:
        class: '%datatable.class%'
        arguments: [ '@service_container' ]
        scope: prototype

    datatable.twig.extension:
        class: Ali\DatatableBundle\Twig\Extension\AliDatatableExtension
        arguments: [ '@service_container' ]
        tags:
            -  { name: twig.extension }

    datatable.twig.routing.extension:
        class: Ali\DatatableBundle\Twig\Extension\RoutingNoRequirementsExtension
        arguments: [ '@datatable.router' ]
        tags:
            -  { name: twig.extension }