language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: 5.6
    - php: 7.0
    
  fast_finish: true
  
  include:
    - php: 5.4
      env: SYMFONY_VERSION='2.6.*' COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
      
    - php: 5.5
      env: SYMFONY_VERSION='2.8.*' 
      
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 5.6
      env: SYMFONY_VERSION='3.0.*'
      
    - php: 7.0
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.0
      env: SYMFONY_VERSION='3.0.*'
      
  
before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; else composer require --dev --no-update symfony/symfony; fi
  
install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - phpunit --coverage-text
  
notifications:
  email: ali.hichem@mail.com