language: php

php:
  - 5.3
  - 5.4
  
env:
  - SYMFONY_VERSION=v2.0.7
  - SYMFONY_VERSION=v2.0.8
  - SYMFONY_VERSION=v2.0.9
  - SYMFONY_VERSION=origin/master
  
before_script: php vendor/vendors.php
